# Numpy (Numerical Python)

### 1. 넘파이 설치 확인

In [2]:
import numpy as np
print(np.__version__)

2.0.1


### 2. 넘파이 배열 (ndarray) 생성과 속성 확인

In [3]:
a1 = np.array([1, 2, 3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
a2 = np.array((1, 2, 3))
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [4]:
a3 = np.array([[1, 2, 3], [4, 5, 6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [5]:
a1 = np.array([1, 2, 3], dtype=float)
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)

[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [6]:
a6 = np.array([1, 4, 5, '8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [7]:
a6 = np.array([1, 4, 5, '8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [8]:
test_list = [[1, 4, 5, 8], [1, 4, 5]] # 갯수가 다르면 안됨
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3. 인덱싱 (indexing)

In [9]:
d = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(d[0], d[1], d[2], d[-1], d[-2])
d[3] = 100
print(d)

1 2 3 9 8
[  1   2   3 100   5   6   7   8   9]


In [10]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0][0])
print(d2[0, 0])
print(d2[1, 1])
print(d2[1, -1])
d2[1, 1] = 100
print(d2)

1
1
7
10
[[  1   2   3   4   5]
 [  6 100   8   9  10]]


In [11]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3[0][0][0])
print(d3[0, 0, 0])
print(d3[1, 1, 2])
print(d3[-1, -1, -1])
d3[1, 1, 1] = 1000
print(d3)

0
0
11
11
[[[   0    1    2]
  [   3    4    5]]

 [[   6    7    8]
  [   9 1000   11]]]


In [12]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [13]:
d3[0] = 50
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [14]:
d3[1, 0] = 30
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[30 30 30]
  [ 9 10 11]]]


### 4. 슬라이싱 (Slicing)

In [15]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [16]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0])
print(d2[0,::2])
print(d2[:, :-1])
print(d2[::2, ::2])

[1 2 3 4 5]
[1 3 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [21]:
d3 = np.arange(12).reshape(2, 2, -1)
print(d3)
print(d3[:, :-1, :-1])
print(d3[:, 1:, 1:])
print(d3[:, :, -1])
print(d3[:, -1, -1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [25]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2)
print(d2[::2, ::3])
d2[::2, ::3] = 30
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]


In [18]:
d2 = np.arange(1, 11).reshape(2, -1)  # -1이라고 쓰면 알아서 계산해줌, 5라고 써도됨
print(d2)
d2[:, :] = -1
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### 5. 불 인덱싱 (Boolean indexing)

In [23]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data > 3)
print(data[data > 3])

[ True  True  True False False False]
[4 6 7]


In [30]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data[(data > 2) & (data < 6)])
print(data[data % 2 == 0])
print(data[data < data.mean()])

[4 3]
[4 6 2 0]
[3 2 0]


### 6. 팬시 인덱싱 (Fancy indexing)

In [31]:
f = np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
f[indexes]

array([6, 7, 4, 7, 7, 7])

In [32]:
f2 = np.array([[1, 4], [9, 16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
f2[x, y]

array([ 1,  9,  9, 16,  4,  4])

### 7. 넘파이 배열의 정렬 (sort)

In [36]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

numbers.sort()
print(numbers)

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [40]:
arr2d = np.array([[5, 6, 7, 8],
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d, axis = 1))
print(np.sort(arr2d, axis = 0))

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [35]:
# argsort() 이용하기, [연습문제] 성적순으로 출력 (내림차순)
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

scores_sorted_index = np.argsort(scores)[::-1]
print(scores_sorted_index)

print(names[scores_sorted_index])

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


### 8. 넘파이 배열의 사칙연산

In [45]:
x = np.arange(1, 7).reshape(2, 3)
print(x)
print(x + x)
print(x + 2)
y = np.array([10, 20, 30])
print(x + y)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
[[11 22 33]
 [14 25 36]]


### 9. 넘파이 배열의 주요 연산 함수

In [56]:
d5 = np.arange(1, 10).reshape(3, -1)
print(d5)
print(d5.sum(axis = 0))
print(d5.sum(axis = 1))
print(d5.mean(axis = 0))
print(d5.mean(axis = 1))
print(d5.max(axis = 0))
print(d5.max(axis = 1))
print(d5.min(axis = 0))
print(d5.min(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[2. 5. 8.]
[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


In [60]:
d5 = np.arange(1, 10).reshape(3, -1)
print(d5.argmax(axis = 0))
print(d5.argmax(axis = 1))
print(d5.argmin(axis = 0))
print(d5.argmin(axis = 1))

[2 2 2]
[2 2 2]
[0 0 0]
[0 0 0]


### 10. any(), all() 함수의 활용

In [63]:
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data)))

True


In [65]:
arr1 = np.array([1, 2, 4])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2))

False
